{
 "title": "Wordpress exporter dashboard",
 "time": { "from": "2019-08-07T06:27:04.504Z", "to": "2019-08-07T06:36:42.549Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of leads",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wordpress_num_users_metric{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of leads",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wordpress_num_users_metric{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "leads"
    }
   ]
  },
  {
   "title": "Number of comments",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wordpress_num_comments_metric{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of comments",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wordpress_num_comments_metric{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "comments"
    }
   ]
  },
  {
   "title": "Number of posts",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wordpress_num_posts_metric{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of posts",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wordpress_num_posts_metric{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "posts"
    }
   ]
  },
  {
   "title": "Number of sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wordpress_num_sessions_metric{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of sessions",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wordpress_num_sessions_metric{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "sessions"
    }
   ]
  },
  {
   "title": "Pending WH",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wordpress_webhooks{kubernetes_namespace=~\"$namespace\", status=\"pending\"}"
    }
   ]
  },
  {
   "title": "In-Progress WH",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "wordpress_webhooks{kubernetes_namespace=~\"$namespace\", status=\"in-progress\"}"
    }
   ]
  },
  {
   "title": "Number of webhooks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wordpress_webhooks{kubernetes_namespace=~\"$namespace\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}