[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true