name: Docker Image CI

on:
  push:
    tags:
      - '*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract git tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: alexandreio
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: alexandreio/wordpress_exporter:latest,alexandreio/wordpress_exporter:${{ env.RELEASE_VERSION }}
